version: 2
updates:
  - package-ecosystem: "npm"
    directory: "extensions/ql-vscode"
    schedule:
      interval: "weekly"
      day: "thursday" # Thursday is arbitrary
    labels:
      - "Update dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday" # Thursday is arbitrary
    labels:
      - "Update dependencies"
